spring.application.name=HospitalManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=postgres

server.servlet.context-path=/api/v1
#//automatically update in database but in production level we can write validate or none
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.defer-datasource-initialization=true
##spring.sql.init.mode=embedded
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#security config
#spring.security.user.name=kumar
#spring.security.user.password=pass

jwt.secretKey = addfhjt18749626wfrjwmkdsoiethe78891fkkejiosw684fwkejtois96287wwiomvmfjnthiw14775swioegfkjla78

